### ISSUE TITLE
showing :no such file or directory

### ISSUE THREAD

**Issue by RCCodeBase** [wsilva/container-from-scratch-demo#1]
I used to get the below error when executing go program

root@ubuntu-xenial:/demo# ./demo run echo "Qualquer coisa / Anything"
--Entrando no conteiner / Get into container--
--Imagem usada echo / Image in use echo --
--Rodando comando [Qualquer coisa / Anything] / Running command [Qualquer coisa / Anything] --
panic: no such file or directory

goroutine 1 [running]:
main.doStuff(0x4ea2e0, 0x549138)
        /demo/demo.go:78 +0x4a
main.fork()
        /demo/demo.go:52 +0x1e9
main.main()
        /demo/demo.go:19 +0x6e
--Saindo do conteiner / Exiting container--
panic: exit status 2

goroutine 1 [running]:
main.doStuff(0x4ea2a0, 0xc42007e0a0)
        /demo/demo.go:78 +0x4a
main.run()
        /demo/demo.go:39 +0x4d2
main.main()
        /demo/demo.go:17 +0x9f

**Comment by wsilva** [comment]
Sorry for the delay.

I think I figured out what happened. As explained here 👉 https://github.com/wsilva/container-from-scratch-demo#10-navigating-between-tags there is one tag for each example.

```bash
$ git tag --list
demo1
demo2
demo3
demo4
demo5
demo6
demo7
```

To check the differences between tags we can run `git diff demo1..demo2` or `git diff demo2..demo3` for instance.

Judging by the output you posted the code must be from one of this tags: `demo4`, `demo5`, `demo6`, or `demo7`, or even `master` branch because it expects you pass an image name before the command.

You can see it in the 3rd line of the output you posted ***Image in use echo*** 

If you run `./demo run debian echo "Qualquer coisa / Anything"` or `./demo run fedora echo "Qualquer coisa / Anything"` or any other base image pre-baked in this vagrant box (alpine, centos, debian, fedora, ubuntu) it must work.

Thanks for reporting. I will try to updade this readme with better explanation or with the step by step commands to run each demos in my next spare time.

**Comment by RCCodeBase** [comment]
Thank you
